[tool.poetry]
name = "datadog_lambda"
version = "2.26.0"
description = "The Datadog AWS Lambda Library"
authors = ["Datadog, Inc. <dev@datadoghq.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/DataDog/datadog-lambda-pyhon"
keywords = [
    "datadog", 
    "aws", 
    "lambda", 
    "layer",
]
packages = [
    { include = "datadog_lambda" }
]
classifiers = [
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]

[tool.poetry.dependencies]
python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*, <4"
datadog = "^0.39.0"
aws-xray-sdk = "^2.6.0"
ddtrace = "^0.44.0"
wrapt = "^1.11.2"

[tool.poetry.dev-dependencies]
boto3 = "^1.10.33"
requests = "^2.22.0"
nose2 = "^0.9.1"
flake8 = "^3.7.9"
importlib-metadata = {version = "^1.0", python = "<3.8"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
